import Head from "next/head";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import HomePage from "@/component/basic/homeLayout";
// import fs from "../styles/fs.css"

export default function Home() {
  return (
    <>
      <Head>
        <title>TMMOB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    
      </Head>
      <HomePage />
    </>
  );
}
